import type { Metadata } from "next";
import "@/styles/globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <div className="relative min-h-screen">
    
    <div className="relative p-6 z-10 flex items-start text-pv-text-primary">
      <div className="flex-1 flex flex-col">
        <main className="flex-1">
          {children}
        </main>
      </div>
      </div>
    </div>
);
}

